version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gymdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gymdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  java-backend:
    build: ./java-backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: Zk9pQ2x1bWJpQnJhbmRvbVNlY3JldEtleTEyMzQ1Njc4
      JWT_EXPIRATION: 60
      GYMAPP_DB_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gymdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      postgres:
        condition: service_healthy

  python-backend:
    build: ./python-backend
    ports:
      - "8000:8000"
    environment:
      # Para producción usarías Postgres aquí
      DATABASE_URL: postgresql://postgres:root@postgres:5432/gymdb
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - java-backend
      - python-backend

  # === Servicio OPCIONAL PARA TESTS (pytest) ===
  python-tests:
    build: ./python-backend
    command: pytest -q
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Tests seguirán usando SQLite (aislado)
      DATABASE_URL: sqlite:///./test_notes.db

volumes:
  postgres_data:
